version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/ChatSaaS_DB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root@2025
      - OPENAI-API-KEY=${OPENAI-API-KEY}
      - JWT_SECRET=${JWT_SECRET:my-secret-key}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET:my-refresh-secret-key}
    depends_on:
      - db
    networks:
      - chatbot-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root@2025
      - MYSQL_DATABASE=ChatSaaS_DB
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge

volumes:
  mysql-data: 